---
title: "Tarea 5"
output: html_document
---
**Viviana Fabres, Consuelo Meza y Diego Parra**

## Pregunta 3
```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(gridExtra)
```
### Pregunta a

Si exsite sesgo debido a la omisión de una variable relevante. 
```{r cars} 
set.seed(123)
reps = 10000
betas = matrix(NA ,nrow = reps, ncol = 16)

beta0 = 2
beta1 = 2.5
beta2 = 1

su = 1

n = c(50, 100, 500, 1000)

for (j in 1:length(n)){
  X1 = rnorm(n[j],20,1)
  X2a = (0.8*X1) + rnorm(n[j],0,1)
  X2b = runif(n[j],0,1)
  
  for (i in 1:reps) {
    
    u = rnorm(n[j],0,su)
    v = beta2*X2a + u
    
    Y0 = beta0 + beta1*X1 + v
    Y1 = beta0 + beta1*X1 + beta2*X2a + u
    
    model0 = lm(Y0 ~ X1)
    betas[i,j] = model0$coef[1]
    betas[i,j+4] = model0$coef[2]
    
    model1 = lm(Y1 ~ X1 + X2a)
    betas[i,j+8] = model1$coef[1]
    betas[i,j+12] = model1$coef[2]
    }
}

betas_df = data.frame(betas)

apply(betas_df, 2, mean)
apply(betas_df, 2, var)
```

### Pregunta b

```{r message=FALSE, warning=FALSE}

m0_50 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,5],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,5]), sd=sd(betas_df[,5])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=50") +xlab(expression(hat(beta)[1])) +
  theme_bw()

m0_50

m0_100 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,6],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,6]), sd=sd(betas_df[,6])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=100") +xlab(expression(hat(beta)[1])) +
  theme_bw()

m0_100

m0_500 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,7],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,7]), sd=sd(betas_df[,7])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=500") +xlab(expression(hat(beta)[1])) +
  theme_bw()

m0_500

m0_1000 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,8],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,8]), sd=sd(betas_df[,8])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=1000") +xlab(expression(hat(beta)[1])) +
  theme_bw()

m0_1000

m1_50 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,13],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,13]), sd=sd(betas_df[,13])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=50") +xlab(expression(hat(beta)[1])) +
  theme_bw()

m1_50

m1_100 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,14],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,14]), sd=sd(betas_df[,14])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=100") +xlab(expression(hat(beta)[1])) +
  theme_bw()

m1_100

m1_500 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,15],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,15]), sd=sd(betas_df[,15])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=500") +xlab(expression(hat(beta)[1])) +
  theme_bw()

m1_500

m1_1000 = ggplot(betas_df) + 
  geom_histogram(aes(betas_df[,16],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(betas_df[,16]), sd=sd(betas_df[,16])),
                geom = "line", color="red", size=1) +
  ylab("Densidad") + ggtitle("n=1000") +xlab(expression(hat(beta)[1])) +
    theme_bw()
  
  m1_1000
  
```